config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # post 'comment', to: 'comments#create'

  get 'movies', to: 'movies#index'

  resources :movies do
    resources :reviews do
      resources :comments
    end
  end

  root "reviews#index"
  post "movies/search", to: 'movies#search', as: :search_movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates :review_id, :user_id, :description, presence: true
  validates :description, length: { minimum: 5, maximum: 100}
  validates :user, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user, foreign_key: 'reviewer_id'
  has_many :comments

  validates :reviewer_id, :movie_id, :score, :title, :content, :conclusion, presence: true
  validates_uniqueness_of :reviewer_id, { :scope => :movie_id }
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validate :reviewer_validation

  def reviewer_validation
    return if user.nil?
    if self.user.type_of_user != 0
      errors.add :user, "is not a valid reviewer"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, foreign_key: 'reviewer_id'
  has_many :comments
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, :email, :type_of_user, presence: true
  validates :username, length: { minimum: 3, maximum: 25}, uniqueness: { case_sensitive: false }
  validates :email, length: { maximum: 250 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  before_action :set_api_key

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to login_path, flash: { danger: "You must be logged in to perform that action."}
    end
  end

  private

    def set_api_key
      Tmdb::Api.key(ENV['API_KEY'])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new()
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to movie_review_path(@comment.review.movie_id, @comment.review_id)
    else
      render :new, status: 422
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:review_id, :user_id, :description)
  end
end

app/controllers/movies_controller.rb
require 'themoviedb'

class MoviesController < ApplicationController

  def index

    @title = params[:genre]
    @genre = Tmdb::Genre.find(params[:genre])
    render :index
  end

  def show
    @movie = Tmdb::Movie.detail(params[:id])
    @reviews = Review.where(movie_id: params[:id])
    render :show
  end

  def search
    @movies = Tmdb::Movie.find(search_params)
    @search_term = search_params
  end

  private

    def search_params
      params.require(:search)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user, only: [:show]
  def index
    @movies = Tmdb::Movie.popular
    @reviews = Review.all.sort_by {|review| review.comments.count }
    render :index
  end

  def new
    @movie = Tmdb::Movie.detail(params[:id])
    @review = Review.new
    render :new
  end

  def create

    @review = Review.new(review_params)
    if @review.save
      redirect_to movie_review_path(@review.movie_id, @review.id)
    else
      render :new, status: 422
    end
  end

  def show
    @review = Review.find_by_id(params[:id])
    @comments = @review.comments
    render :show
  end

  private

    def review_params
      params.require(:review).permit(:reviewer_id, :content, :conclusion, :score, :title, :movie_id)
    end

    def require_user
      redirect_to login_path if !logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user), flash: {success: "You have successfully logged in."}
    else
      flash.now[:danger] = "Invalid email or password."
      render :new, status: 401
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: {success: "You have successfully logged out."}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.username}."
      redirect_to user_path(@user)
    else
      render :new, status: 422
    end
  end

  def show
    @user = User.find(current_user.id)
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :type_of_user)
    end

    def require_user
      redirect_to login_path if !logged_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=retro"
  end
end

app/views/comments/new.html.erb
<%= render "shared/errors", object: @comment %>
<div class="container">
  <h3 align="center">Leave a comment</h3>
  <div class="row">
    <%= form_for(@comment, html: { class: "form-horizontal", role: "form" }, url: movie_review_comments_path) do |f| %>
    <%= f.text_field :user_id, type: "hidden", value: current_user.id %>
    <%= f.text_field :review_id, type: "hidden", value: params[:review_id] %>
    <div class="form-group">
      <div class="col-sm-2 control-label">
        <%= f.label :description %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :description, class: "form-control", placeholder: "Add a comment", autofocus: true %>
      </div>
      <%= f.submit "Publish", class: "btn btn-primary" %>
    </div>
    <% end %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright ©
      <a href="#">CritiqueHub</a>
      by
      <a href="https://github.com/kwokhuen/client_project">Two Thumbs Up</a>
      <p>Powered by:<br> <%= image_tag "mdb", size: "40x40"%></p>
    </small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% if flash %>
<div class="rows">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |status, msg| %>
      <div class="alert alert-dismissible alert-<%= status %>" role="alert">
        <a href="#" class="close" aria-label="close" data-dismiss="alert">&times;</a>
        <%= content_tag :div, msg, id: "flash_#{status}" if msg.is_a? String %>
      </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/layouts/_navigation.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to image_tag("logo.png", size: "100x74", class: "logo"), root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Genre <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
          <li><%= link_to current_user.username, user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/movies/index.html.erb
<h1 align="center"><%= @title %></h1><br>

<% @genre.results.each do |movie| %>
    <%= link_to image_tag("https://image.tmdb.org/t/p/w500/#{movie['poster_path']}", class: "search-img"), "/movies/#{movie['id']}" %>
<% end %>

app/views/movies/search.html.erb
<h1 align="center">Search Result of "<%= @search_term %>"</h1><br>

<% @movies.each do |movie| %>
    <%= link_to image_tag("https://image.tmdb.org/t/p/w500/#{movie.poster_path}", class: "search-img"), "/movies/#{movie.id}" %>
<% end %>

app/views/movies/show.html.erb
<div class="row">
  <div class="col-md-4">
    <img id="movie-page-poster" src="https://image.tmdb.org/t/p/w500/<%=@movie["poster_path"]%>">
  </div>
  <div class="col-md-5 col-md-offset-1">
    <h3 align="center">Average Rating:<br> <%= @movie["vote_average"] %> out of 10</h3>
  </div>
  <div class="col-md-5 col-md-offset-1">
    <div class="well movie-title card-panel">
      <h2><%= @movie["title"] %></h2>
      <p><%= @movie["overview"] %></p>
    </div>
  </div>
</div>

<div class="container">

  <% @reviews.each do |review| %>

  <div class="well review-info card-panel">
    <h4><%= review.title %></h4>
    <h6>Score: <%= review.score %> / 5 </h6>
    <p><%= truncate(review.conclusion, length: 150){ link_to "Continue", movie_review_path(@movie['id'], review.id) } %><p>
      <p><small>Written by <%= review.user.username %> <%= time_ago_in_words(review.created_at) %></small></p>
    </div>
    <%end%>
    <% if logged_in? %>
    <%= link_to "Click here to write a review", new_movie_review_path(@movie['id']), class: "btn btn-primary" %>
    <% end %>
</div>

app/views/reviews/index.html.erb
<div class="row center">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="box">
            <div class="container-1">
                <%= form_tag search_movies_path do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
                    <% submit_tag "Search", :name => nil %>
                <% end %>
            </div>
        </div>
    </div>
</div>

<h2 class="title-homepage">Popular now</h2>
<div class="row movie-slider-home-page">
    <div class="col-md-10 col-md-offset-1">
        <div id="main-slider" class="movie-slider">
            <% @movies.each do |movie| %>
                <div class='poster'>
                    <%= link_to image_tag("https://image.tmdb.org/t/p/w500/#{movie.poster_path}"), "/movies/#{movie.id}" %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<h2 class="title-homepage">Genres</h2>
<div class="row movie-slider-home-page">
<div class="col-md-10 col-md-offset-1">
    <div id="main-slider" class="movie-slider">

        <div class='poster'>
            <%= link_to image_tag("https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4MDU0NTUyN15BMl5BanBnXkFtZTgwMzQxMzY4MjE@._V1_UX182_CR0,0,182,268_AL_.jpg"), "/movies?genre=Action" %>
            <a href='/movies?genre=Action'>
                Action
            </a>
        </div>

        <div class='poster'>
            <%= link_to image_tag("https://images-na.ssl-images-amazon.com/images/M/MV5BMjEwMzMxODIzOV5BMl5BanBnXkFtZTgwNzg3OTAzMDI@._V1_SX214_AL_.jpg"), "/movies?genre=Adventure" %>
            <a href='/movies?genre=Adventure'>
                Adventure
            </a>
        </div>

        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//z4x0Bp48ar3Mda8KiPD1vwSY3D8.jpg"), "/movies?genre=Animation" %>
            <a href='/movies?genre=Animation'>
                Animation
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//inVq3FRqcYIRl2la8iZikYYxFNR.jpg"), "/movies?genre=Comedy" %>
            <a href='/movies?genre=Comedy'>
                Comedy
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//oFOG2yIRcluKfTtYbzz71Vj9bgz.jpg"), "/movies?genre=Crime" %>
            <a href='/movies?genre=Crime'>
                Crime
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//hBdcsiqtZR916eFpkCnQGkzN5lb.jpg"), "/movies?genre=Documentary" %>
            <a href='/movies?genre=Documentary'>
                Documentary
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//h6O5OE3ueRVdCc7V7cwTiQocI7D.jpg"), "/movies?genre=Drama" %>
            <a href='/movies?genre=Drama'>
                Drama
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//hGRfWcy1HRGbsjK6jF7NILmqmFT.jpg"), "/movies?genre=Family" %>
            <a href='/movies?genre=Family'>
                Family
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//xMvzfhXZdfeLBZZUIQRB4vw1EtA.jpg"), "/movies?genre=Fantasy" %>
            <a href='/movies?genre=Fantasy'>
                Fantasy
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//noUp0XOqIcmgefRnRZa1nhtRvWO.jpg"), "/movies?genre=History" %>
            <a href='/movies?genre=History'>
                History
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//lw0IqOSMsQcy1QnVIEIDppLmNwk.jpg"), "/movies?genre=Horror" %>
            <a href='/movies?genre=Horror'>
                Horror
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//s9ye87pvq2IaDvjv9x4IOXVjvA7.jpg"), "/movies?genre=Music" %>
            <a href='/movies?genre=Music'>
                Music
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//gdiLTof3rbPDAmPaCf4g6op46bj.jpg"), "/movies?genre=Mystery" %>
            <a href='/movies?genre=Mystery'>
                Mystery
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//kHXEpyfl6zqn8a6YuozZUujufXf.jpg"), "/movies?genre=Romance" %>
            <a href='/movies?genre=Romance'>
                Romance
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg"), "/movies?genre=Science%20Fiction" %>
            <a href='/movies?genre=Science%20Fiction'>
                Science Fiction
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//84FbbKA1Knskhxh2gXtkH9nM8QP.jpg"), "/movies?genre=TV%20Movie" %>
            <a href='/movies?genre=TV%20Movie'>
                TV Movie
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//lFSSLTlFozwpaGlO31OoUeirBgQ.jpg"), "/movies?genre=Thriller" %>
            <a href='/movies?genre=Thriller'>
                Thriller
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//svPHnYE7N5NAGO49dBmRhq0vDQ3.jpg"), "/movies?genre=War" %>
            <a href='/movies?genre=War'>
                War
            </a>
        </div>
        <div class='poster'>
            <%= link_to image_tag("https://image.tmdb.org/t/p/w500//wfPHdfofBD5PN96dV96a51B3Ja2.jpg"), "/movies?genre=Western" %>
            <a href='/movies?genre=Western'>
                Western
            </a>
        </div>
    </div>
</div>
</div>

<h2 class="title-homepage center">Popular Reviews</h2>
<div class="container">
  <% @reviews.each do |review| %>
  <div class="well review-info card-panel">
    <h4><%= review.title %></h4>
    <h6>Score: <%= review.score %> / 5 </h6>
    <p><%= truncate(review.conclusion, length: 150){ link_to "Continue", movie_review_path(review.movie_id, review.id) } %><p>
      <p><small>Written by <%= review.user.username %> <%= time_ago_in_words(review.created_at) %></small></p>
    </div>
    <%end%>

</div>

app/views/reviews/new.html.erb
<h1 align="center">Create a New Review</h1>


<%= render "shared/errors", object: @review %>
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <%= form_for(@review, html: { class: "form-horizontal", role: "form" }, url: movie_reviews_path) do |f| %>

      <%= f.text_field :reviewer_id, type: "hidden", value: current_user.id %>

      <%= f.text_field :movie_id, type: "hidden", value: params[:movie_id] %>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Your review title", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :content %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :content, class: "form-control", placeholder: "Your review", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :conclusion %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :conclusion, class: "form-control", placeholder: "Your conclusion", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :score %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :score, class: "form-control", placeholder: "Your final score (from 1 to 5)", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Publish", class: "btn btn-primary" %>
        </div>
      </div>

      <% end %>

    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<h1 align="center"><%= @review.title%></h1>
<h2 align="center"><%= @review.score %> out of 5</h2>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="well card-panel center">
      <%= image_tag gravatar_for(current_user, size: 150, align: "center" ), class: "img-circle" %>
      <p><small><%= @review.user.username %></small></p>
      <p><%= @review.content %></p>
      <p><%= @review.conclusion %></p>
    </div>
    <!-- <small>Reviews: <%= current_user.reviews.count %></small> -->

  </div>
</div>
<h4 align="center">Comments</h4>
<div class="row">
    <div class="col-md-5 col-md-offset-1">
      <% @comments.each do |comment| %>
      <div class="well user-review-info card-panel">
        <h5>@<%= comment.user.username %></h5>
        <p><%= comment.description %></p>
        <small>Comment <%= time_ago_in_words(comment.created_at) %></small>
        </div>
        <% end %>
        <div class="col-md-5 col-md-offset-1">
          <%= link_to "Add a comment", new_movie_review_comment_path(@review.movie_id, @review.id), class: "btn btn-primary" %>
      </div>
    </div>
  <!-- <div class="col-md-5">
    <div class="well user-review-info card-panel">
      <h3>Review Title</h3>
      <p>Review Conclusion<p>
        <p>Review Score</p>
        <p>Author Name</p>
      </div>
  </div> -->

</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="rows">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3><%= pluralize(object.errors.count, "error") %></h3>
        </div>
        <div class="panel-body">
          <ul>
            <% object.errors.full_messages.each do |error| %>
            <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render "shared/errors", object: @user %>
<div class="container">
  <div class="row">
    <h1 align="center">Create an account</h1>
    <div class="col-xs-8 col-xs-offset-2">

      <%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :user_type %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :type_of_user ,class: "form-control", placeholder: "Reviewer: 0 | Normal User: 1", autofocus: true %>
        </div>
      </div>





      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Password", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Sign Up", class: "btn btn-primary" %>
        </div>
      </div>

      <% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 align="center">Your Profile</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <div>
      <%= image_tag gravatar_for(current_user, size: 150, align: "center" ), class: "img-circle" %>
    </div>
    <small>Reviews: <%= current_user.reviews.count %></small>

  </div>
</div>
<h4 align="center">Your Reviews</h4>
<div class="container">

  <% @user.reviews.each do |review| %>

  <div class="well review-info card-panel">
    <h4><%= review.title %></h4>
    <h6>Score: <%= review.score %> / 5 </h6>
    <p><%= truncate(review.conclusion, length: 150){ link_to "Continue", movie_review_path(@movie['id'], review.id) } %><p>
      <p><small>Written by <%= review.user.username %> <%= time_ago_in_words(review.created_at) %></small></p>
    </div>
    <%end%>
</div>